version: "3.2"
services:
  mcs_converter:
    image: mcs_converter:latest
    container_name: mcs_converter
    restart: always
    privileged: true
    environment:
      - DB_HOST=34.66.39.220
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=dbpass
      - DB_PORT=5432
      - SEPARATOR_SO=/
      - BUCKET_GOOGLE=bucket-converter-web-app
      - PATH_BUCKET_KEY=misw4204-202312-swnube-bucket.json
      - PATH_PUBSUB_KEY=misw4204-202312-swnube-pub-sub.json
      - PATH_TOPIC=projects/misw4204-202312-swnube/topics/tasks-topic
    build: .
    working_dir: /app/
    ports:
      - 80:80
    volumes:
      - .:/app/
    networks:
      - convert_network
  
networks:
  convert_network:
    driver: bridge