version: "3.2"
services:
  mcs_converter:
    image: mcs_converter:latest
    container_name: mcs_converter
    restart: always
    privileged: true
    environment:
      - DB_HOST=34.27.130.169
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=dbpass
      - DB_PORT=5432
      - SEPARATOR_SO=/
      - BUCKET_GOOGLE=bucket-converter-web-app
      - PATH_BUCKET_KEY=misw4204-202312-swnube-bucket.json
      - PATH_PUBSUB_KEY=misw4204-202312-swnube-pub-sub.json
      - PATH_TOPIC=projects/misw4204-202312-swnube/topics/tasks-topic
    command: sh run_commands.sh
    build: ./services
    working_dir: /backend/
    volumes:
      - ./services/:/backend/
    networks:
      - convert_network
  
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - convert_network
    depends_on:
      - mcs_converter

networks:
  convert_network:
    driver: bridge