version: "3.2"
services:
  
  mcs_converter:
    restart: always
    image: mcs_converter:latest
    environment:
      - SEPARATOR_SO=/
    command: sh run_commands.sh
    volumes:
      - ./services/:/backend/
    build: ./services
    working_dir: /backend/
    container_name: mcs_converter
    networks:
      - convert_network
    #depends_on:
    #  - postgres
    #  - rabbitmq_broker
  
  nginx_proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx_proxy
    restart: always
    networks:
      - convert_network
    depends_on:
    #  - postgres
    #  - rabbitmq_broker
      - mcs_converter

networks:
  convert_network:
    driver: bridge