version: "3.2"
services:
  mcs_converter:
    restart: always
    image: mcs_converter:latest
    privileged: true
    environment:
      - DB_HOST=34.135.240.95
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=dbpass
      - DB_PORT=5432
      - SEPARATOR_SO=/
      - RABBIT_HOST=10.128.0.6
      - HOME_PATH=/home/stonejfg/misw-cloud-storage
    command: sh run_commands.sh
    volumes:
      # - ./services/:/backend/
      - nfs_shared:/home/stonejfg/misw-cloud-storage      
    build: ./services
    working_dir: /backend/
    container_name: mcs_converter
    networks:
      - convert_network
  
  nginx_proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx_proxy
    restart: always
    networks:
      - convert_network
    depends_on:
      - mcs_converter

volumes:
  nfs_shared:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=misw-cloud-storage,rsize=65536,wsize=65536,timeo=14,tcp,rw,noatime"
      device: ":/home/stonejfg/misw-cloud-storage"

networks:
  convert_network:
    driver: bridge