version: "3.2"
services:
  rabbitmq_broker:
    image: "rabbitmq:3.9.13-management"
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ConverterUser
      - RABBITMQ_DEFAULT_PASS=ConverterPass
    networks:
      - convert_network

  celery_worker:
    image: celery_worker:latest
    privileged: true
    environment:
      - C_FORCE_ROOT=true
      - HOME_PATH=/home/stonejfg/misw-cloud-storage
      - SEPARATOR_SO=/
      - DB_HOST=34.135.240.95
      - DB_USER=postgres
      - DB_PASS=dbpass
      - DB_NAME=postgres
    build: .
    working_dir: /backend/
    volumes:
      #- nfs_shared:/home/stonejfg/misw-cloud-storage
      - /home/stonejfg/misw-cloud-storage:/home/stonejfg/misw-cloud-storage
    command: celery -A worker.celery worker --pool=solo -l info
    container_name: celery_worker
    restart: always
    networks:
      - convert_network
    depends_on:
      - rabbitmq_broker

#volumes:
#  nfs_shared:
#    driver: local
#    driver_opts:
#      type: "nfs"
#      o: "addr=gs://misw-cloud-storage,rsize=65536,wsize=65536,timeo=14,tcp,rw,noatime"
#      device: ":/home/stonejfg/misw-cloud-storage"

networks:
  convert_network:
    driver: bridge
