version: "3.2"
services:
  worker:
    image: worker:latest
    environment:
      - PORT=80
      - SEPARATOR_SO=/
      - DB_HOST=34.66.39.220
      - DB_USER=postgres
      - DB_PASS=dbpass
      - DB_NAME=postgres
      - PATH_PRIVATE_KEY=misw4204-202312-swnube-bucket.json
    build: .
    working_dir: /backend/
    ports:
      - 80:80
    volumes:
      - .:/backend/
    container_name: worker
    restart: always    
    networks:
      - convert_network

networks:
  convert_network:
    driver: bridge
