version: "3.2"
services:
  worker:
    image: worker:latest
    privileged: true
    environment:
      - C_FORCE_ROOT=true
      - SEPARATOR_SO=/
      - DB_HOST=192.168.0.10
      - DB_USER=postgres
      - DB_PASS=dbpass
      - DB_NAME=postgres
      - PATH_PRIVATE_KEY=misw4204-202312-swnube-bucket.json
    build: .
    working_dir: /backend/
    volumes:
      - .:/backend/
    command: gunicorn --bind 0.0.0.0:80 app:app
    container_name: worker
    restart: always
    networks:
      - convert_network

networks:
  convert_network:
    driver: bridge
